"""empty message

Revision ID: 41e070075f86
Revises: ae48f0e68703
Create Date: 2024-02-24 14:02:23.870025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e070075f86'
down_revision = 'ae48f0e68703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('class_one_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('class_two_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('class_three_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('class_four_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('class_five_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('class_six_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('class_seven_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('class_eight_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('class_nine_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('class_ten_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('class_eleven_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('class_twelve_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('strength', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dexterity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('constitution', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('intelligence', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wisdom', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('charisma', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.drop_column('charisma')
        batch_op.drop_column('wisdom')
        batch_op.drop_column('intelligence')
        batch_op.drop_column('constitution')
        batch_op.drop_column('dexterity')
        batch_op.drop_column('strength')
        batch_op.drop_column('class_twelve_name')
        batch_op.drop_column('class_eleven_name')
        batch_op.drop_column('class_ten_name')
        batch_op.drop_column('class_nine_name')
        batch_op.drop_column('class_eight_name')
        batch_op.drop_column('class_seven_name')
        batch_op.drop_column('class_six_name')
        batch_op.drop_column('class_five_name')
        batch_op.drop_column('class_four_name')
        batch_op.drop_column('class_three_name')
        batch_op.drop_column('class_two_name')
        batch_op.drop_column('class_one_name')
        batch_op.drop_column('race')

    # ### end Alembic commands ###